### ISSUE TITLE
Cannot download the weight files from Ipython

### ISSUE THREAD

**Issue by mkd1996** [churchlab/UniRep#23] opened 2021-01-06 00:56 UTC
I am having problem in downloading the files from the unirep tutorial file. I have cloned the repository and after  following the guidance provided in here, I am stuck in running the unirep_tutorial.ipynb and I am getting the following error. I would really appreciate if you guide me in this issue. 

Thank you so much,
Mehrsa

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-13-421267aa98ba> in <module>
      1 batch_size = 12
----> 2 b = babbler(batch_size=batch_size, model_path=MODEL_WEIGHT_PATH)

~\OneDrive\Documents\GitHub\UniRep\unirep.py in __init__(self, model_path, batch_size)
    727                             num_layers=self._num_layers,
    728                             model_path=model_path,
--> 729                             wn=self._wn)
    730         zero_state = rnn.zero_state(self._batch_size, tf.float32)
    731         single_zero = rnn.zero_state(1, tf.float32)

~\OneDrive\Documents\GitHub\UniRep\unirep.py in __init__(self, num_units, num_layers, dropout, res_connect, wn, scope, var_device, model_path)
    256             gmx_init=np.load(join(bs + "{0}_mlstm_stack{1}_gmx:0.npy".format(i,i))),
    257             gmh_init=np.load(join(bs + "{0}_mlstm_stack{1}_gmh:0.npy".format(i,i)))
--> 258                  ) for i in range(self._num_layers)]
    259         if self._dropout:
    260             layers = [

~\OneDrive\Documents\GitHub\UniRep\unirep.py in <listcomp>(.0)
    256             gmx_init=np.load(join(bs + "{0}_mlstm_stack{1}_gmx:0.npy".format(i,i))),
    257             gmh_init=np.load(join(bs + "{0}_mlstm_stack{1}_gmh:0.npy".format(i,i)))
--> 258                  ) for i in range(self._num_layers)]
    259         if self._dropout:
    260             layers = [

~\anaconda3\envs\py37\lib\site-packages\numpy\lib\npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    414             own_fid = False
    415         else:
--> 416             fid = stack.enter_context(open(os_fspath(file), "rb"))
    417             own_fid = True
    418 

FileNotFoundError: [Errno 2] No such file or directory: './64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wx:0.npy'

**Comment by mkd1996** [comment] 2021-01-06 19:32
Also using !aws s3 sync --no-sign-request --quiet s3://unirep-public/64_weights/ 64_weights/ to directly download the weights it gives me a folder with no information. 

Thanks, 
Mehrsa

**Comment by surgebiswas** [comment] 2021-01-07 21:36
Hey Mehrsa,

The command works for me. Can you remove the --quiet flag and let me know what output you get?

Surge

Surge Biswas

**Comment by mkd1996** [comment] 2021-01-08 14:18
Hey Surge, 

Thank you for your response.

The following is what happens when I try to download the files even after removing the quiet flag.

Thanks,
Mehrsa

download failed: s3://unirep-public/64_weights/fully_connected_biases:0.npy to 64_weights\fully_connected_biases:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\fully_connected_biases:0.npy.8dc2CdF2' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\fully_connected_biases:0.npy'
download failed: s3://unirep-public/64_weights/embed_matrix:0.npy to 64_weights\embed_matrix:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\embed_matrix:0.npy.7dBbb3a2' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\embed_matrix:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gh:0.npy.1dD04fEa' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_b:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_b:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_b:0.npy.AaC7FdCD' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_b:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gmx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gmx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gmx:0.npy.80b0619a' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gmx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gx:0.npy.ed0FB9da' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gx:0.npy'
download failed: s3://unirep-public/64_weights/fully_connected_weights:0.npy to 64_weights\fully_connected_weights:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\fully_connected_weights:0.npy.D35e5DCF' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\fully_connected_weights:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gmh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gmh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gmh:0.npy.A0B5E63E' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_gmh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gh:0.npy.30bB3972' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wh:0.npy.53311EfB' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wx:0.npy.FaeaA8Ff' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gmh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gmh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gmh:0.npy.8BDB23c0' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gmh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wmx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wmx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wmx:0.npy.05bd5fea' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wmx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gx:0.npy.Bede4593' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gmx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gmx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gmx:0.npy.e31DeEcA' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_gmx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_b:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_b:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_b:0.npy.d2aeF00f' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_b:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wmx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wmx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wmx:0.npy.B58154D5' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wmx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wh:0.npy.4D75eC4c' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gmx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gmx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gmx:0.npy.88b1F02f' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gmx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_b:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_b:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_b:0.npy.aedA55Fc' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_b:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wmh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wmh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wmh:0.npy.6FDa73c9' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wmh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gx:0.npy.fce5F63B' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gh:0.npy.a23Cb9cA' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gmh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gmh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gmh:0.npy.E823bDAf' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_gmh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wmh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wmh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wmh:0.npy.F0642aD3' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wmh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gh:0.npy.26f890d1' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_b:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_b:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_b:0.npy.df9d88b4' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_b:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gmh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gmh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gmh:0.npy.e3A32cEC' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gmh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wx:0.npy.Af5BeF7a' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack1_mlstm_stack1_wx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gmx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gmx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gmx:0.npy.c9c61d6A' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gmx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wmx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wmx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wmx:0.npy.E15972E9' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wmx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wmh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wmh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wmh:0.npy.a5e3dF2A' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack0_mlstm_stack0_wmh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wx:0.npy.0E72c4dd' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gx:0.npy.2b2ecff2' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_gx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wh:0.npy.E4FebeCc' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack2_mlstm_stack2_wh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wmx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wmx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wmx:0.npy.7e02b15D' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wmx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wmh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wmh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wmh:0.npy.a8BA6D2C' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wmh:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wx:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wx:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wx:0.npy.E9575b49' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wx:0.npy'
download failed: s3://unirep-public/64_weights/rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wh:0.npy to 64_weights\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wh:0.npy [WinError 87] The parameter is incorrect: 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wh:0.npy.ffA0d33d' -> 'C:\\Users\\me2ma\\OneDrive\\Documents\\GitHub\\UniRep\\64_weights\\rnn_mlstm_stack_mlstm_stack3_mlstm_stack3_wh:0.npy'

**Comment by nekitmm** [comment] 2021-02-22 19:14
Having the same problem here. Any updates on this?

**Comment by surgebiswas** [comment] 2021-02-22 19:20
@Mardikor did you figure this out? It still works for me on mac/linux and have others tell me it works for them as well. I suspect this could be a windows issue. @nekitmm Are you on windows? 

I don't have access to a windows machine, but this might be of use (Googling @Mardikor's error): https://stackoverflow.com/questions/48627793/oserror-winerror-87the-parameter-is-incorrect

**Comment by surgebiswas** [comment] 2021-02-22 19:41
Closing this issue for now, but please re-open if it's still an issue. 

Some members of the community  have also created a great re-implementation of UniRep in JAX: https://github.com/ElArkk/jax-unirep . You may consider giving that a try and see if it resolves your issues.

**Closed as completed by surgebiswas** 2021-02-22 19:41 UTC

**Comment by mkd1996** [comment] 2021-02-22 20:14
I am still having the same issue but as you mentioned it might be the windows problem.

 Thanks for your comments and updates.
Mehrsa
________________________________

**Comment by nekitmm** [comment] 2021-02-22 20:26
Yes, it seems to be a windows issue - I think the problem is ':' symbol in the filenames, which is reserved in NTFS.
